Repository utaipei-sa/reserve.utsa, pull requests merged in 2024-07, with the labels that each got.

#5 Urf 6 refactor all
  .env
  jsconfig.json
  src/api/index.js
  src/api/reserve.js
  src/components/basic/DatePicker.vue
  src/components/form/BasicInfo.vue
  src/components/form/ItemDisplay.vue
  src/components/form/ItemSelector.vue
  src/components/form/SpaceDisplay.vue
  src/components/form/SpaceSelector.vue
  src/components/form/SubmitDialog.vue
  src/components/layout/AppBar.vue
  src/components/timetable/TimeTableDisplay.vue
  src/components/timetable/TimeTableSelector.vue
  src/pages/form.vue
  src/pages/timetable.vue
  src/pages/verify.vue
Labels: Improvement

#12 Feat response dialog
  src/api/reserve.js
  src/api/response.js
  src/components/basic/ResponseDialog.vue
  src/components/form/ItemSelector.vue
  src/components/form/SpaceSelector.vue
  src/components/form/SubmitDialog.vue
  src/pages/edit.vue
  src/pages/form.vue
Labels: enhancement

#13 Feat/verify
  src/api/index.js
  src/api/reserve.js
  src/api/response.js
  src/components/form/ItemDisplay.vue
  src/components/form/ItemSelector.vue
  src/components/form/SpaceDisplay.vue
  src/components/form/SpaceSelector.vue
  src/components/form/SubmitDialog.vue
  src/pages/edit.vue
  src/pages/verify.vue
Labels: bug
