Repository utaipei-sa/reserve.utsa, pull requests merged in 2024-08, with the labels that each got.

#10 Feat :edit and delete page
  src/api/index.js
  src/api/reserve.js
  src/api/response.js
  src/components/form/SubmitDialog.vue
  src/pages/edit.vue
  src/pages/form.vue
Labels: enhancement

#25 ci :lint setting
  .eslintrc.js
  .github/workflows/lint.yml
  .prettierignore
  .prettierrc.js
  index.html
  jsconfig.json
  package-lock.json
  package.json
  src/App.vue
  src/api/index.js
  src/api/reserve.js
  src/api/response.js
  src/components/README.md
  src/components/basic/DatePicker.vue
  src/components/basic/ResponseDialog.vue
  src/components/form/BasicInfo.vue
  src/components/form/ItemDisplay.vue
  src/components/form/ItemSelector.vue
  src/components/form/SpaceDisplay.vue
  src/components/form/SpaceSelector.vue
  src/components/form/SubmitDialog.vue
  src/components/layout/AppBar.vue
  src/components/timetable/TimeTableDisplay.vue
  src/components/timetable/TimeTableSelector.vue
  src/main.js
  src/pages/edit.vue
  src/pages/form.vue
  src/pages/index.vue
  src/pages/timetable.vue
  src/pages/verify.vue
  src/plugins/index.js
  src/plugins/vuetify.js
  src/router/index.js
Labels: enhancement

#27 feat :disable-mail-in-edit
  src/components/form/BasicInfo.vue
  src/pages/edit.vue
  src/pages/form.vue
Labels: bug

#26 fix :timezone problem
  src/components/form/SubmitDialog.vue
  src/pages/edit.vue
Labels: Improvement

#32 fix :dockerfile and nginx
  Dockerfile
  nginx/nginx.conf
Labels: bug

#33 Feat: Coloring
  src/components/basic/DatePicker.vue
  src/components/basic/ResponseDialog.vue
  src/components/form/BasicInfo.vue
  src/components/form/ItemDisplay.vue
  src/components/form/ItemSelector.vue
  src/components/form/SpaceDisplay.vue
  src/components/form/SpaceSelector.vue
  src/components/form/SubmitDialog.vue
  src/components/layout/AppBar.vue
  src/components/timetable/TimeTableDisplay.vue
  src/components/timetable/TimeTableSelector.vue
  src/main.js
  src/pages/edit.vue
  src/pages/form.vue
  src/pages/index.vue
  src/pages/timetable.vue
  src/plugins/vuetify.js
  src/styles/settings.scss
Labels: enhancement

#38 Feat/loader
  src/components/basic/CircularLoader.vue
  src/components/form/SubmitDialog.vue
  src/components/timetable/TimeTableLoader.vue
  src/components/timetable/TimeTableSelector.vue
  src/pages/edit.vue
  src/pages/form.vue
  src/pages/index.vue
  src/pages/timetable.vue
  src/styles/settings.scss
Labels: enhancement
